# Generated by Django 6.0.6 on 2026-06-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discord_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
