# Generated by Django 5.2.7 on 2025-10-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronly', '0002_rename_date_added_cronjob_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='interval_seconds',
            field=models.IntegerField(default=300, help_text='Ping interval in seconds'),
        ),
    ]
