# Generated by Django 5.2.7 on 2025-10-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronly', '0005_cronjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='last_pinged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
