# Generated by Django 5.2.7 on 2025-10-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronly', '0006_cronjob_last_pinged_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='last_pinged_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='target',
            field=models.URLField(),
        ),
    ]
