# Generated by Django 5.2.7 on 2025-10-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronjob',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
