# Generated by Django 5.2.7 on 2025-10-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_cronjob_interval_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='interval_seconds',
            field=models.IntegerField(default=300),
        ),
    ]
