# Generated by Django 6.0.6 on 2026-06-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0007_alter_cronjob_last_pinged_at_alter_cronjob_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='avg_rtt_ms',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='last_pinged_at',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='max_rtt_ms',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='min_rtt_ms',
        ),
    ]
