# Generated by Django 6.0.6 on 2026-06-28 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0008_remove_cronjob_avg_rtt_ms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CronJob',
            new_name='Monitor',
        ),
    ]
